
trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Hello, world changed!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'  
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo JOb-2!
    displayName: 'Run a one-line script'




