
trigger:
- master

pool:
  vmImage: $(operatingSystem)

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo Build fisrtjob
    - bash: echo $(PipelineLavelBariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(Build.SourceBranchName)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
# - stage: DevDeploy
#   variables:
#     env: Dev
#   jobs: 
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(env)Deploy Devjob
# - stage: QADeploy
#   jobs: 
#   - job: QADeployJob
#     steps:
#     - bash: echo QADeploy fisrtjob
# - stage: ProdDeploy
#   jobs: 
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeploy fisrtjob



